### ISSUE TITLE
I can't see any copied file

### ISSUE THREAD

**Issue by billy84** [dsgriffin/ionic-3-file-transfer-example#1]
Hi,

I am new to ionic.
Did you test your project?
I got these errors when I build the project on Mac terminal.

home.ts(10,10): Error TS2339: Property 'platform' does not exist on type 'HomePage'
home.ts(11,10): Error TS2339: Property 'nav' does not exist on type 'HomePage'
home.ts(12,10): Error TS2339: Property 'image' does not exist on type 'HomePage'
home.ts(16,10): Error TS2339: Property 'platform' does not exist on type 'HomePage'
home.ts(17,32): Error TS2304: Cannot find name 'FileTransfer'
home.ts(18,32): Error TS2304: Cannot find name 'cordova'
home.ts(23,16): Error TS2339: Property 'platform' does not exist on type 'HomePage'.
home.ts(27,16): Error TS2339: Property 'platform' does not exist on type 'HomePage'.
home.ts(28,22): Error TS2304: Cannot find name 'cordova'.
home.ts(30,20): Error TS2339: Property 'platform' does not exist on type 'HomePage'.
home.ts(31,22): Error TS2304: Cannot find name 'cordova'.
home.ts(46,18): Error TS2339: Property 'nav' does not exist on type 'HomePage'.
home.ts(56,18): Error TS2339: Property 'nav' does not exist on type 'HomePage'.

I can launch this project on xCode but I can't see any copied files.

Can you help me?

Regards,

**Comment by dsgriffin** [comment]
Hi @billy84,

While this project is using an out-of-date version of Ionic 2 beta (and Angular 2 beta), it still works fine for me. The TypeScript errors you are getting are an issue between Ionic and TypeScript and don't affect the application compiling fine.

Once you've built, open up xCode with your device connected and run the application - then go to `window` (on the top menu in xCode), click `devices` then select the installed app by double clicking (in this case `Ionic2FileTransferExample`).

It should then show you the file structure - once you've tapped on the download button in-app, the `cute-pug.jpg` will appear in the `Documents/` like so:

<img width="336" alt="screen shot 2016-06-08 at 23 35 24" src="https://cloud.githubusercontent.com/assets/4924254/15913486/35478f66-2dd2-11e6-8ab9-1c32dfddc59f.png">

Regardless, I've just updated the project to use much newer versions of everything.

**Comment by dsgriffin** [comment]
Let me know if there's still any issues for you, cheers!

**Comment by billy84** [comment]
Hi @dsgriffin,

Sorry for the delay.
Yes, your project is working well.

Thanks,
