### ISSUE TITLE
Error : Cannot find name 'cordova'.

### ISSUE THREAD

**Issue by devangmistry13** [dsgriffin/ionic-3-file-transfer-example#12]
i applied the same code to my project but is shows this error : 

    L25:    this.storageDirectory = cordova.file.documentsDirectory;

            Cannot find name 'cordova'.

      L27:  else if(this.platform.is('android')) {
      L28:    this.storageDirectory = cordova.file.dataDirectory;

            Cannot find name 'cordova'.

      L43:        const imageLocation = `${cordova.file.applicationDirectory}www/assets/img/${image}`;

**Comment by dsgriffin** [comment]
hi @devangmistry13, in `declaration.d.ts` I declared `cordova` as `declare var cordova: any;`, so make  sure you have that

**Comment by dsgriffin** [comment]
Let me know if you have any more issues, closing

**Comment by Sophia0322** [comment]
Hi, I have met the same problem, but in ionic3, there is no _declaration.d.ts_ file, so i can't type _declare var crdova:any;_ in it. I tried to type it to _home.ts,_ _main.ts._..etc., but they were all not working. Please help me!! Thank you so much.

**Comment by dsgriffin** [comment]
@Sophia0322 hi. it should work in one of the pages. I moved it to [home.ts](https://github.com/dsgriffin/ionic-3-file-transfer-example/blob/0e7b1af42ddc6ea9b2a2ed81d6f4e2ed6aed7d2c/src/pages/home/home.ts#L7) in my example a few months ago
