### ISSUE TITLE
Error: Current working directory is not a Cordova-based project. While adding platform

### ISSUE THREAD

**Issue by simerjit-fwrk** [dsgriffin/ionic-3-file-transfer-example#13]
Error: Current working directory is not a Cordova-based project. While adding platform

**Comment by dsgriffin** [comment]
@simerjit-fwrk Run `mkdir www` inside your project root

**Comment by dsgriffin** [comment]
@simerjit-fwrk let me know if this resolved your issue :)

**Comment by Muzaffar08** [comment]
when i create platform then this message occure
No platforms added to this project. Please use `cordova platform add <platform>`.

**Comment by Muzaffar08** [comment]
'ionic-app-scripts' is not recognized as an internal or external command,
operable program or batch file.

this error occur when I run this command "ionic build android --prod"

**Comment by dsgriffin** [comment]
@Muzaffar08 `npm install @ionic/app-scripts@latest --save-dev`
