### ISSUE TITLE
Facing this issue .. can anyone help me?

### ISSUE THREAD

**Issue by baltejsingh88** [dsgriffin/ionic-3-file-transfer-example#14]
<img width="319" alt="screen shot 2017-06-05 at 3 50 35 pm" src="https://cloud.githubusercontent.com/assets/16228380/26780349/0fe25326-4a07-11e7-8f3e-97ba67074973.png">

**Comment by dsgriffin** [comment]
@codecrab-studios is that an emulator? accessing storage will only work on a real device

**Comment by baltejsingh88** [comment]
@dsgriffin yes in Emulator its not working,  but in iPhone Device  when we save that image, it doesn't show up in the Photo Gallery!

**Comment by dsgriffin** [comment]
@codecrab-studios iOS is quite restricted as to where you can store files directly, [see the full list of places here](https://github.com/apache/cordova-plugin-file#where-to-store-files), usually best way is to sync with iCloud

**Comment by dsgriffin** [comment]
If you have any more issues just let me know! closing

**Comment by coolvasanth** [comment]
Hi @dsgriffin  Below is my target path to store the files on iOS.
`cordova.file.syncedDataDirectory;`
Even the download is happening successfully for various MIME types like .jpeg, .pdf etc. But all the files are stored on the app's sandbox storage. So user can view it, only if he connects his phone to Mac machine in iTunes Connect. I want user to show a popup where user can choose the drive apps(iCloud, Google Drive etc) to download and save the file. How to achieve it ?
