### ISSUE TITLE
ERROR Error: Uncaught (in promise): ReferenceError: cordova is not defined

### ISSUE THREAD

**Issue by navenchary** [dsgriffin/ionic-3-file-transfer-example#17]
I have downloaded the files setup the code in my local machine. I am using ionic cli 3.8. When I ran the command ionic serve, it gave me the below warnings.

`[WARN] Detected @ionic/cli-plugin-cordova in your package.json.
       As of CLI 3.8, it is no longer needed. You can uninstall it:
        npm uninstall --save-dev --save-exact @ionic/cli-plugin-cordova
[WARN] Detected @ionic/cli-plugin-ionic-angular in your package.json.
       As of CLI 3.8, it is no longer needed. You can uninstall it:
       npm uninstall --save-dev --save-exact @ionic/cli-plugin-ionic-angular`

When the app was displayed in the browser, clicking on the download button was throwing the below error message
`ERROR Error: Uncaught (in promise): ReferenceError: cordova is not defined`
And clicking on the retrieve download image was throwing the `File retrieval Failed!` alert message.

**Comment by dsgriffin** [comment]
Sorry for the missed reply - this only works on iOS/Android devices, please see the [requirements/build steps](https://github.com/dsgriffin/ionic-3-file-transfer-example#requirements)
