### ISSUE TITLE
Error code 3

### ISSUE THREAD

**Issue by astoryx** [dsgriffin/ionic-3-file-transfer-example#18]
I have all dependencies installed, when running on both iOS and Android device I get an Error code: 3. It doesn't explain what the error is so I'm finding hard to solve. I've also looked through any relevant documentation but couldn't seem to find anything. Any help? Thanks.

**Comment by dsgriffin** [comment]
That's a [connection error](https://ionicframework.com/docs/native/file-transfer/#FileTransferErrorCode), are you running the app on your devices as outlined [here](https://ionicframework.com/docs/intro/deploying/)?

**Comment by astoryx** [comment]
I certainly am, please see the attached screen shot. I have run via ionic serve and through packaging the app and running through Xcode.
![img_0924](https://user-images.githubusercontent.com/29950763/33832967-e405acfe-de75-11e7-9c6c-a5c18b284bf8.jpeg)

**Comment by dsgriffin** [comment]
What do the logs in Xcode say when the tap the download button? Are you having any other connection issues with these devices?

**Comment by dsgriffin** [comment]
I'll be closing this for now as it's seemingly an internet connection issue
