### ISSUE TITLE
Does this FileTransfer plugin works?

### ISSUE THREAD

**Issue by prasath003** [dsgriffin/ionic-3-file-transfer-example#19]
I have tried in android and ios both the logs say download is successful but when i check the directory, the file is not there

**Comment by dsgriffin** [comment]
@prasath003 [`retrieveImage`](https://github.com/dsgriffin/ionic-3-file-transfer-example/blob/master/src/pages/home/home.ts#L74) confirms whether the image is indeed at the selected location or not. What does that show when you click it?

Also if you want to physically see these directories you will need to check out the answers [here for iOS](https://stackoverflow.com/q/15219511/1586880) and something like [this for Android](https://stackoverflow.com/q/32842604/1586880)

**Comment by dsgriffin** [comment]
Let me know if you have any more issues!

**Comment by prasath003** [comment]
@dsgriffin  Am using Rooted Android 7.1.2 Phone and iOS Jailbreak 10.1.1. I went and checked the files folder in both it's not getting downloaded, only change is downloading directly from server link will it be an issue??

**Comment by dsgriffin** [comment]
If you click `Retrieve downloaded image` what does the dialog popup say? It should show the location of where you stored the file. 

If you are downloading from a server link it will be fine but of course will need to change some things such as `imageLocation` and `image` variables inside `downloadImage()`

**Comment by prasath003** [comment]
This gives me success, but the file is not getting downloaded.

const fileTransfer: FileTransferObject = this.transfer.create();
        const url = 'https://someserver/file.pdf';
        fileTransfer.download(url, this.file.dataDirectory + 'file.pdf').then((entry) => {
          console.log('download complete: ' + this.file.dataDirectory);
        }, (error) => {
            console.log("download error :"+error)
        });

I think am doing something wrong,anyway thank you @dsgriffin.
