### ISSUE TITLE
IOS

### ISSUE THREAD

**Issue by Ross-Rawlins** [dsgriffin/ionic-3-file-transfer-example#2]
Have you had any issues where on IOS if you call the file its doesnt work? Did you have to use a cdvn file extension?

**Comment by dsgriffin** [comment]
Nope - and I'm unaware of what a .cdvn file extension is. Do you have an example of the issue?

**Comment by Ross-Rawlins** [comment]
its just an extra extension in part of file:// ie cdvfile://. I am just looking to solve an issue where once I download the file and I try to call it in the app on IOS it fails. And I ma not sure where the bug may lie.

**Comment by dsgriffin** [comment]
If this issue is still relevant to you, I've updated the project to use a much newer version of Ionic 2 alongside the Ionic Native version of `cordova-plugin-file-transfer`. 

There's a section at the bottom of the README talking about checking if a file exists/reading it back etc.
