### ISSUE TITLE
Read back file

### ISSUE THREAD

**Issue by iRoachie** [dsgriffin/ionic-3-file-transfer-example#3]
How would you read back in the file? I've tried using the url from target path, but on iOS it gives me an error.

Failed to load resource: The operation couldn’t be completed. Operation not permitted

**Comment by dsgriffin** [comment]
Hi, sorry for the really delayed reply. I've updated the example to use the new `ionic-native` lib for transferring files which makes things slightly easier.

You'd use the ionic-native [File](https://ionicframework.com/docs/v2/native/file/) module for that - just had a quick play with it on this example and it read back the file fine.

**Comment by iRoachie** [comment]
Yea can close this. I got it done using `File.readAsDataURL()` method. Thanks
