### ISSUE TITLE
Android Download file not working

### ISSUE THREAD

**Issue by MuslimMunir** [dsgriffin/ionic-3-file-transfer-example#4]
Hi, 
I have configured your project and installed the apk on my device and on pressing download image button I received message box that file is downloaded to folder but in that folder file is not present.

Actually I tried your solution as a workout of my problem in which I am using pdfmake to make a pdf file and download but your download file also didn't worked so I think its an issue with ionic2.

**Comment by dsgriffin** [comment]
How are you checking for the presence of that file? You can use either [`adb`](https://github.com/dsgriffin/ionic-2-file-transfer-example#android-1) or the [`File` module](https://ionicframework.com/docs/v2/native/file/) just after downloading it to confirm it's there

**Comment by MuslimMunir** [comment]
I am checking by navigating to folder and that folder is empty.

**Comment by dsgriffin** [comment]
You won't be able to see it on Android using a file explorer (see the relevant mention of that here: https://ionicframework.com/docs/v2/native/transfer/). 

They advise testing it using `adb`, but maybe using the relevant methods from `File` to confirm it's there programmatically after download is more reusable.

**Comment by MuslimMunir** [comment]
So what to do in case if I have to save that file and use that file in future using mobile app and share that file to someone

**Comment by dsgriffin** [comment]
Download it, check that it downloaded ok etc. Then when you need it, you can retrieve it using methods provided by [`File`](https://ionicframework.com/docs/v2/native/file/). Then you'd use the `upload` method to send it elsewhere

**Comment by MuslimMunir** [comment]
Thanks for quick help on this. I will try to complete the flow as you explained.

**Comment by dsgriffin** [comment]
No worries. Let me know how it goes!
