### ISSUE TITLE
Got an error when calling the upload, and no native function is called(i tried NSLog)

### ISSUE THREAD

**Issue by chenyu1990** [dsgriffin/ionic-3-file-transfer-example#5]
in the log, the path exists, and i used the File.checkFile

error is
`{"line":951,"column":37,"sourceURL":"file:///var/containers/Bundle/Application/084ED2B6-958F-4206-94B2-322892B84A41/tongzhanbu.app/www/cordova.js"}`
or
`{"line":2,"column":xxx,"sourceURL":"file:///var/containers/Bundle/Application/084ED2B6-958F-4206-94B2-322892B84A41/tongzhanbu.app/www/build/polyfills.js"}`
when the Transfer.upload.error

plz save me...

**Comment by dsgriffin** [comment]
Hi @ninechung, I will need to see the code that is producing this error so I can try to investigate it myself. Thanks

**Comment by dsgriffin** [comment]
Let me know if you can provide any more info about this issue. My guess is your problem is related to file paths you are trying to use. Will close this issue for now but let me know if you need it reopened.
