### ISSUE TITLE
Cant find variable FileTransfer

### ISSUE THREAD

**Issue by yasar-salim** [dsgriffin/ionic-3-file-transfer-example#6]
when running this project it shows a runtime error cant find variable FileTransfer

**Comment by dsgriffin** [comment]
@yasar-salim Are you using the latest version of this example? As it was recently updated to use the Ionic Native Transfer module 

```
import {Transfer} from 'ionic-native';
...
const fileTransfer = new Transfer();
```

If there's still an issue try installing the plugin manually (`ionic plugin add cordova-plugin-file-transfer`)
