### ISSUE TITLE
Unable to find downloaded image

### ISSUE THREAD

**Issue by SanjayYadav90** [dsgriffin/ionic-3-file-transfer-example#9]
I am unable to find downloaded image either in mac or iPhone.
The path is being display there, does not available over there in device.
Here is my mac local setup-

```
******************************************************
Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: 5.0.8 
OS: OS X Yosemite
Node Version: v6.2.2
Xcode version: Xcode 7.2 Build version 7C68
******************************************************
```

How to find that image!!!

**Comment by dsgriffin** [comment]
Hi @SanjayYadav90, first of all you mention Mac, but it will require a real iOS device (so it will not work on emulator etc.) 

You can retrieve the file using Ionic Native's [`File`](https://ionicframework.com/docs/v2/native/file/) module, like how it is being used [here](https://github.com/dsgriffin/ionic-2-file-transfer-example/blob/master/src/pages/home/home.ts#L69) and then do whatever you want with it.

**Comment by bukosabino** [comment]
I try to find downloaded image with a Android file manager such as ASTRO (https://play.google.com/store/apps/details?id=com.metago.astro&hl=es)
Is it possible?

**Comment by dsgriffin** [comment]
@bukosabino see https://github.com/dsgriffin/ionic-2-file-transfer-example/issues/4#issuecomment-260759467, the docs (at the time) mentioned using either `adb` or the Ionic Native `File` module to retrieve the file
